services:
   db:
     image: postgres:15
     container_name: task_db
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: 1214
       POSTGRES_DB: task_manager
     ports:
         - "5433:5433"
     volumes:
         - postgres_data:/var/lib/postgresql/data
volumes:
   postgres_data: